{
  imports = [
    ./hyprland/cursor.nix
    ./hyprland/hyprland.nix
    ./hyprland/hyprtoolkit.nix
    ./hyprland/power.nix
    ./hyprland/swaync.nix
    ./hyprland/waybar.nix
    ./hyprland/wofi.nix
    ./programs/hytale.nix
    ./programs/kitty.nix
    ./programs/obs.nix
    ./programs/vscodium.nix
    ./programs/zen.nix
    ./default-apps.nix
    ./env.nix
    ./packages.nix
    ./pfp.nix
    ./program-wrappers.nix
    ./scripts.nix
  ];
}
